import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSelector } from "react-redux";
import { ThemeProvider } from "styled-components";
import WordCloud from "../components/Charts/Cloud/WordCloud";
import Chart2by2 from "../components/Charts/2by2";
import GlobalWeights from "../components/GlobalWeights/GlobalWeights";
import Decisions from "../components/Decisions";
import Collateral from "../components/Collateral";
import DecisionTree from "../components/Decisions/DecisionTree";

const Matrix = dynamic(() => import("../components/matrix/Matrix"), {
  ssr: false,
});
const OrgChart = dynamic(() => import("../components/Charts/OrgChart/index"), {
  ssr: false,
});
const MindMap = dynamic(() => import("../components/Charts/MindMap/index"), {
  ssr: false,
});
const Fishbone = dynamic(() => import("../components/Charts/Fishbone"), {
  ssr: false,
});

export default function Home() {
  const { chartCellDimensions } = useSelector((state) => state.matrix);
  const { showState } = useSelector((state) => state.app);

  const switchComponent = () => {
    switch (showState) {
      case "matrix":
        return <Matrix />;
      case "fishbone":
        return <Fishbone />;
      case "orgChart":
        return <OrgChart />;
      case "mindMap":
        return <MindMap />;
      case "wordCloud":
        return <WordCloud />;
      case "2by2":
        return <Chart2by2 />;
      case "globalWeights":
        return <GlobalWeights />;
      case "decisions":
        return <Decisions />;
      case "collateral":
        return <Collateral />;
      case "decisionTree":
        return <DecisionTree />;
      default:
        return <Matrix />;
    }
  };

  return (
    <ThemeProvider
      theme={{
        chartCellWidth: chartCellDimensions.width,
        chartCellHeight: chartCellDimensions.height,
      }}
    >
      <div className={styles.container}>
        <Head>
          <title>Ideagens</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {switchComponent()}
      </div>
    </ThemeProvider>
  );
}
