import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Home.module.css";
// import OrgChart from "../components/Charts/OrgChart";
import { useSelector } from "react-redux";
import { ThemeProvider } from "styled-components";

const Matrix = dynamic(() => import("../components/matrix/Matrix"), {
  ssr: false,
});
const OrgChart = dynamic(() => import("../components/Charts/OrgChart"), {
  ssr: false,
});

export default function Home() {
  const { showState, chartCellDimensions } = useSelector(
    (state) => state.matrix
  );
  return (
    <ThemeProvider
      theme={{
        chartCellWidth: chartCellDimensions.width,
        chartCellHeight: chartCellDimensions.height,
      }}
    >
      <div className={styles.container}>
        <Head>
          <title>Ideagens</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {showState === "chart" ? <OrgChart /> : <Matrix />}
      </div>
    </ThemeProvider>
  );
}
