import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Matrix = dynamic(() => import("../components/matrix/Matrix"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ideagens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Matrix />
    </div>
  );
}
