const frameworks = {
  "5M+2S": [
    [
      "LEVEL1/CATEGORY",
      "LEVEL2/CAUSES",
      "LEVEL3/IDEAS01",
      "LEVEL3/IDEAS02",
      "LEVEL3/IDEAS03",
      "LEVEL3/IDEAS04",
      "IDEAS05/Level3",
      "LEVEL3/IDEAS06",
      "LEVEL3/IDEAS07",
      "LEVEL3/IDEAS08",
    ],
    ["MEN", "Quality"],
    ["MEN", "Quantity"],
    ["MEN", "Availability"],
    ["MATERIALS", "Quality"],
    ["MATERIALS", "Quantity"],
    ["MATERIALS", "Availability"],
    ["MACHINES", "Quality"],
    ["MACHINES", "Quantity"],
    ["MACHINES", "Availability"],
    ["MONEY", "Quantity/Budget"],
    ["MONEY", "Cost/Borrowing/IRR"],
    ["MONEY", "Availability/Timing"],
    ["METHODS", "Technologies"],
    ["METHODS", "Labor Intensive/Machine Intensive"],
    [
      "METHODS",
      "Single Source Of Truth (SSOT)/Multiple Version of Truth (MVOT)",
    ],
    ["SYSTEMS", "Centralization/Decentralization"],
    ["SYSTEMS", "Open/closed"],
    ["SYSTEMS", "On-Premise/On-Cloud"],
    ["STRATEGY", "Cost/Feature Differentiation"],
    ["STRATEGY", "Outcome Management"],
    ["STRATEGY", "Defensive/Offensive"],
    ["STRATEGY", "In House/Outsourced"],
  ],
  "Risk Analysis": [
    [
      "LEVEL1",
      "LEVEL2",
      "Confidence Level",
      "Probability of Event",
      "Cost of Event",
      "Risk Value",
    ],
    ["Assumptions", "External Environment", 0, 0],
    ["Assumptions", "Competitive Environment", 0, 0],
    ["Assumptions", "Internal Environment", 0, 0],
    ["Assumptions", "Time Frame to Solve", 0, 0],
    ["Assumptions", "365 View or Limited", 0, 0],
    ["Identify Threats", "Human", "CxDxE"],
    ["Identify Threats", "Operational", "CxDxE"],
    ["Identify Threats", "Reputational", "CxDxE"],
    ["Identify Threats", "Procedural", "CxDxE"],
    ["Identify Threats", "Project", "CxDxE"],
    ["Identify Threats", "Financial", "CxDxE"],
    ["Identify Threats", "Technical", "CxDxE"],
    ["Identify Threats", "Natural", "CxDxE"],
    ["Identify Threats", "Political", "CxDxE"],
    ["Identify Threats", "Structural", "CxDxE"],
    ["Risk Management", "Avoid the Risk"],
    ["Risk Management", "Share the Risk"],
    ["Risk Management", "Accept the Risk"],
    [
      "Risk Management",
      "Control the Risk",
      "Business Experiment",
      "Preventive Action",
      "Detective Action",
    ],
  ],
  BSC: [
    [
      "Perspectives",
      "Sub-Perspective",
      "Leaves01",
      "Leaves02",
      "Leaves03",
      "Leaves04",
      "Leaves05",
    ],
    [
      "Financial Perspective",
      "ROI",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Financial Perspective",
      "EVA",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Financial Perspective",
      "Revenue",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Financial Perspective",
      "Earnings",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Financial Perspective",
      "Capital",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
    ],
    [
      "Financial Perspective",
      "Cash Flows",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
      "KPI07",
    ],
    [
      "Customer Perspecive",
      "Quality",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Customer Perspecive",
      "Service",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Customer Perspecive",
      "Pricing",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Customer Perspecive",
      "Time",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Customer Perspecive",
      "Image",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
    ],
    [
      "Customer Perspecive",
      "Relations",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
      "KPI07",
    ],
    [
      "Internal Process Prespective",
      "Production",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Internal Process Prespective",
      "Delivery",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Internal Process Prespective",
      "Marketing",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Internal Process Prespective",
      "Operations",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Internal Process Prespective",
      "Quality Control",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
    ],
    [
      "Internal Process Prespective",
      "Service Dept",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
      "KPI07",
    ],
    [
      "Internal Process Prespective",
      "R&D",
      "KPI04",
      "KPI05",
      "KPI06",
      "KPI07",
      "KPI08",
    ],
    [
      "Learning &Growth Perspective",
      "Employee",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Learning &Growth Perspective",
      "HR Capital",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Learning &Growth Perspective",
      "Knowledge",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Learning &Growth Perspective",
      "Technology",
      "KPI01",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
    ],
    [
      "Learning &Growth Perspective",
      "Best Practices",
      "KPI02",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
    ],
    [
      "Learning &Growth Perspective",
      "Intangibles",
      "KPI03",
      "KPI04",
      "KPI05",
      "KPI06",
      "KPI07",
    ],
  ],
  Unknown: [
    ["Effect", "Cause", "Example 01", "Example 02"],
    ["Known-Effect", "Known-Cause", "No. Of Orders", "Type Of Product Sold"],
    [
      "Known-Effect",
      "Known-Cause",
      "Customer Order",
      "First Time or Returning Customer",
    ],
    ["Known-Effect", "Unknown-Cause", "Revenue Per Order", "Multiple Reasons"],
    ["Known-Effect", "Unknown-Cause", "Churn", "Multiple Reasons"],
    ["Known-Effect", "Unknown-Cause", "Changes in Cart", "Multiple Reasons"],
    [
      "Known-Effect",
      "Unknown-Cause",
      "Order Location",
      "Orders - Multiple Reasons",
    ],
    [
      "Known-Effect",
      "Unknown-Cause",
      "Applicant do not turn up for Interview",
      "Multiple Reasons",
    ],
    ["Unknown-Effect", "Known-Cause", "Multiple Effects", "Great Resignation"],
    ["Unknown-Effect", "Known-Cause", "Multiple Effects", "Lack of Motivation"],
    [
      "Unknown-Effect",
      "Unknown-Cause",
      "Crime - Multiple Effects",
      "Crime Multiple Causes",
    ],
  ],
};

export default frameworks;
