const frameworks = {
  "5M+2S": [
    [
      "LEVEL1/CATEGORY",
      "LEVEL2/CAUSES",
      "LEVEL3/IDEAS01",
      "LEVEL3/IDEAS02",
      "LEVEL3/IDEAS03",
      "LEVEL3/IDEAS04",
      "IDEAS05/Level3",
      "LEVEL3/IDEAS06",
      "LEVEL3/IDEAS07",
      "LEVEL3/IDEAS08",
    ],
    ["MEN", "Quality"],
    ["MEN", "Quantity"],
    ["MEN", "Availability"],
    ["MATERIALS", "Quality"],
    ["MATERIALS", "Quantity"],
    ["MATERIALS", "Availability"],
    ["MACHINES", "Quality"],
    ["MACHINES", "Quantity"],
    ["MACHINES", "Availability"],
    ["MONEY", "Quantity/Budget"],
    ["MONEY", "Cost/Borrowing/IRR"],
    ["MONEY", "Availability/Timing"],
    ["METHODS", "Technologies"],
    ["METHODS", "Labor Intensive/Machine Intensive"],
    [
      "METHODS",
      "Single Source Of Truth (SSOT)/Multiple Version of Truth (MVOT)",
    ],
    ["SYSTEMS", "Centralization/Decentralization"],
    ["SYSTEMS", "Open/closed"],
    ["SYSTEMS", "On-Premise/On-Cloud"],
    ["STRATEGY", "Cost/Feature Differentiation"],
    ["STRATEGY", "Outcome Management"],
    ["STRATEGY", "Defensive/Offensive"],
    ["STRATEGY", "In House/Outsourced"],
  ],
  "Risk Analysis": [
    [
      "LEVEL1",
      "LEVEL2",
      "Confidence Level",
      "Probability of Event",
      "Cost of Event",
      "Risk Value",
    ],
    ["Assumptions", "External Environment", 0, 0],
    ["Assumptions", "Competitive Environment", 0, 0],
    ["Assumptions", "Internal Environment", 0, 0],
    ["Assumptions", "Time Frame to Solve", 0, 0],
    ["Assumptions", "365 View or Limited", 0, 0],
    ["Identify Threats", "Human", "CxDxE"],
    ["Identify Threats", "Operational", "CxDxE"],
    ["Identify Threats", "Reputational", "CxDxE"],
    ["Identify Threats", "Procedural", "CxDxE"],
    ["Identify Threats", "Project", "CxDxE"],
    ["Identify Threats", "Financial", "CxDxE"],
    ["Identify Threats", "Technical", "CxDxE"],
    ["Identify Threats", "Natural", "CxDxE"],
    ["Identify Threats", "Political", "CxDxE"],
    ["Identify Threats", "Structural", "CxDxE"],
    ["Risk Management", "Avoid the Risk"],
    ["Risk Management", "Share the Risk"],
    ["Risk Management", "Accept the Risk"],
    [
      "Risk Management",
      "Control the Risk",
      "Business Experiment",
      "Preventive Action",
      "Detective Action",
    ],
  ],
};

export default frameworks;
